deployment:
  tasks:
    - export DEPLOYPATH=/home/se7entechnet/se7entech-crm
    - export CONFIGPATH=/home/se7entechnet/deploy_config_files
    - /bin/cp -r $CONFIGPATH/vendor $DEPLOYPATH/vendor
    - /bin/cp $CONFIGPATH/.env $DEPLOYPATH/.env
    - /bin/cp $CONFIGPATH/.htaccess $DEPLOYPATH/.htaccess
    - /bin/chmod 750 $DEPLOYPATH/vendor
    - /bin/chmod 640 $DEPLOYPATH/.env
    - /bin/chmod 644 $DEPLOYPATH/.htaccess