deployment:
  tasks:
    # 1. Definir rutas importantes
    - export DEPLOYPATH=/home/se7entechnet/se7entech-crm
    - export CONFIGPATH=/home/se7entechnet/deploy_config_files  # Ruta donde están tus archivos de configuración

    # 2. Instalar dependencias de Composer
    - cd $DEPLOYPATH
    - /usr/local/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader

    # 3. Copiar archivos de configuración
    - /bin/cp $CONFIGPATH/.env $DEPLOYPATH/.env
    - /bin/cp $CONFIGPATH/.htaccess $DEPLOYPATH/.htaccess

    # 4. Ajustar permisos (opcional)
    - /bin/chmod 640 $DEPLOYPATH/.env
    - /bin/chmod 644 $DEPLOYPATH/.htaccess