deployment:
  tasks:
    # 1. Definir rutas importantes
    - export DEPLOYPATH=/home/se7entechnet/se7entech-crm
    - export CONFIGPATH=/home/se7entechnet/deploy_config_files  # Ruta donde están tus archivos de configuración

    # 2. Copiar la carpeta vendor completa (en lugar de composer install)
    - /bin/cp -r $CONFIGPATH/vendor $DEPLOYPATH/vendor

    # 3. Copiar archivos de configuración
    - /bin/cp $CONFIGPATH/.env $DEPLOYPATH/.env
    - /bin/rm -f $DEPLOYPATH/.env.example
    - /bin/cp $CONFIGPATH/.htaccess $DEPLOYPATH/.htaccess
    - /bin/rm -f $DEPLOYPATH/.htaccess.example

    # 4. Ajustar permisos y propietarios
    - /bin/chmod 750 $DEPLOYPATH/vendor
    - /bin/chmod 640 $DEPLOYPATH/.env
    - /bin/chmod 644 $DEPLOYPATH/.htaccess